// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using TaskMirror.Data;

#nullable disable

namespace taskmirrorapidotnet.Migrations
{
    [DbContext(typeof(TaskMirrorDbContext))]
    [Migration("20251112165854_Baseline")]
    partial class Baseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskMirror.Models.Feedback", b =>
            {
                b.Property<int>("IdFeedback")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("id_feedback");

                OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFeedback"));

                b.Property<string>("Conteudo")
                    .IsRequired()
                    .HasMaxLength(1000)
                    .HasColumnType("NVARCHAR2(1000)")
                    .HasColumnName("conteudo");

                b.Property<DateTime>("DataGerado")
                    .HasColumnType("TIMESTAMP(7)")
                    .HasColumnName("data_gerado");

                b.Property<int>("IdTarefa")
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("id_tarefa");

                b.HasKey("IdFeedback");

                b.HasIndex("IdTarefa")
                    .IsUnique();

                b.ToTable("tbl_feedbacks");
            });

            modelBuilder.Entity("TaskMirror.Models.StatusTarefa", b =>
            {
                b.Property<int>("IdStatusTarefa")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("id_status_tarefa");

                OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStatusTarefa"));

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("NVARCHAR2(100)")
                    .HasColumnName("nome");

                b.HasKey("IdStatusTarefa");

                b.ToTable("tbl_status_tarefa");
            });

            modelBuilder.Entity("TaskMirror.Models.Tarefa", b =>
            {
                b.Property<int>("IdTarefa")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("id_tarefa");

                OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTarefa"));

                b.Property<DateTime?>("DataFim")
                    .HasColumnType("TIMESTAMP(7)")
                    .HasColumnName("data_fim");

                b.Property<DateTime?>("DataInicio")
                    .HasColumnType("TIMESTAMP(7)")
                    .HasColumnName("data_inicio");

                b.Property<string>("Descricao")
                    .HasMaxLength(500)
                    .HasColumnType("NVARCHAR2(500)")
                    .HasColumnName("descricao");

                b.Property<int>("IdLider")
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("id_lider");

                b.Property<int>("IdStatusTarefa")
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("id_status_tarefa");

                b.Property<int>("IdTipoTarefa")
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("id_tipo_tarefa");

                b.Property<int>("IdUsuario")
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("id_usuario");

                b.Property<decimal?>("TempoEstimado")
                    .HasColumnType("NUMBER(5,2)")
                    .HasColumnName("tempo_estimado");

                b.Property<decimal?>("TempoReal")
                    .HasColumnType("NUMBER(5,2)")
                    .HasColumnName("tempo_real");

                b.Property<int?>("TipoTarefaIdTipoTarefa")
                    .HasColumnType("NUMBER(10)");

                b.HasKey("IdTarefa");

                b.HasIndex("IdLider");

                b.HasIndex("IdStatusTarefa");

                b.HasIndex("IdTipoTarefa");

                b.HasIndex("IdUsuario");

                b.HasIndex("TipoTarefaIdTipoTarefa");

                b.ToTable("tbl_tarefas");
            });

            modelBuilder.Entity("TaskMirror.Models.TipoTarefa", b =>
            {
                b.Property<int>("IdTipoTarefa")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("id_tipo_tarefa");

                OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoTarefa"));

                b.Property<string>("Nome")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("NVARCHAR2(100)")
                    .HasColumnName("nome");

                b.HasKey("IdTipoTarefa");

                b.ToTable("tbl_tipo_tarefa");
            });

            modelBuilder.Entity("TaskMirror.Models.Usuario", b =>
            {
                b.Property<int>("IdUsuario")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("id_usuario");

                OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                b.Property<string>("Funcao")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("NVARCHAR2(100)")
                    .HasColumnName("funcao");

                b.Property<int?>("IdLider")
                    .HasColumnType("NUMBER(10)")
                    .HasColumnName("id_lider");

                b.Property<string>("Password")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("NVARCHAR2(255)")
                    .HasColumnName("password");

                b.Property<string>("RoleUsuario")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("NVARCHAR2(100)")
                    .HasColumnName("role_usuario");

                b.Property<string>("Username")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("NVARCHAR2(100)")
                    .HasColumnName("username");

                b.HasKey("IdUsuario");

                b.HasIndex("IdLider");

                b.HasIndex("Username")
                    .IsUnique();

                b.ToTable("tbl_usuarios");
            });

            modelBuilder.Entity("TaskMirror.Models.Feedback", b =>
            {
                b.HasOne("TaskMirror.Models.Tarefa", "Tarefa")
                    .WithOne("Feedback")
                    .HasForeignKey("TaskMirror.Models.Feedback", "IdTarefa")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_feedback_tarefa");

                b.Navigation("Tarefa");
            });

            modelBuilder.Entity("TaskMirror.Models.Tarefa", b =>
            {
                b.HasOne("TaskMirror.Models.Usuario", "Lider")
                    .WithMany()
                    .HasForeignKey("IdLider")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired()
                    .HasConstraintName("fk_tarefas_lider");

                b.HasOne("TaskMirror.Models.StatusTarefa", "StatusTarefa")
                    .WithMany()
                    .HasForeignKey("IdStatusTarefa")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired()
                    .HasConstraintName("fk_tarefas_status");

                b.HasOne("TaskMirror.Models.TipoTarefa", "TipoTarefa")
                    .WithMany()
                    .HasForeignKey("IdTipoTarefa")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired()
                    .HasConstraintName("fk_tarefas_tipo");

                b.HasOne("TaskMirror.Models.Usuario", "Usuario")
                    .WithMany()
                    .HasForeignKey("IdUsuario")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired()
                    .HasConstraintName("fk_tarefas_usuario");

                b.HasOne("TaskMirror.Models.TipoTarefa", null)
                    .WithMany("Tarefas")
                    .HasForeignKey("TipoTarefaIdTipoTarefa");

                b.Navigation("Lider");

                b.Navigation("StatusTarefa");

                b.Navigation("TipoTarefa");

                b.Navigation("Usuario");
            });

            modelBuilder.Entity("TaskMirror.Models.Usuario", b =>
            {
                b.HasOne("TaskMirror.Models.Usuario", "Lider")
                    .WithMany("Subordinados")
                    .HasForeignKey("IdLider")
                    .OnDelete(DeleteBehavior.SetNull)
                    .HasConstraintName("fk_usuarios_lider");

                b.Navigation("Lider");
            });

            modelBuilder.Entity("TaskMirror.Models.Tarefa", b =>
            {
                b.Navigation("Feedback");
            });

            modelBuilder.Entity("TaskMirror.Models.TipoTarefa", b =>
            {
                b.Navigation("Tarefas");
            });

            modelBuilder.Entity("TaskMirror.Models.Usuario", b =>
            {
                b.Navigation("Subordinados");
            });
#pragma warning restore 612, 618
        }
    }
}
